# Global settings
nameOverride: ""
fullnameOverride: ""
namespace: "default"

imagePullSecrets:
  - aliyun-registry

# RabbitMQ settings
rabbitmq:
  image:
    repository: docker.io/bitnami/rabbitmq
    tag: 3.9.12-debian-10-r0
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi
    accessMode: ReadWriteOnce

  auth:
    username: guest
    # password will be stored in secret
    password: "Lesso2128"
    existingSecret: ""
    erlangCookie: "uap4rzxW9cXmDLj2vkPEflDb51bd5aLB"

  plugins:
    default: "rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap, rabbitmq_prometheus"
    additional: "rabbitmq_mqtt, rabbitmq_stomp, rabbitmq_web_stomp"

  configuration:
    debug: false
    ulimitNofiles: "65536"
    useLogname: "true"
    loadDefinitions: "no"
    securePassword: "yes"

  service:
    type: ClusterIP
    ports:
      amqp: 5672
      dist: 25672
      stats: 15672
      epmd: 4369
      metrics: 9419
      websocket: 15674

  nodeSelector: {}

# Init container settings
initContainer:
  image:
    repository: docker.io/bitnami/rabbitmq
    tag: 3.9.12-debian-10-r0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Security settings
securityContext:
  fsGroup: 1001
  runAsUser: 1001

# Pod anti-affinity settings
antiAffinity:
  enabled: true
  weight: 1

# Service account settings
serviceAccount:
  create: true
  name: "rabbitmq-cluster" 
# vhost and diskFreeLimit config (optional)
vhost: ""  # Uncomment to set a specific vhost
diskFreeLimit: "50MB"  # disk free limit
totalMemoryAvailable: "8589934592"  # 8GB in bytes
memoryHighWatermark: "0.4"  # memory high watermark 
